#pragma once

#include <exception>

class LoggedSuccessfully : public std::exception {};